theme: minima

title: Your awesome title
author: David Poole
description: > # this means to ignore newlines until "baseurl:"
  'GitHub Pages' test site

# social links
github_username:  davidlpoole # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
